### ISSUE TITLE
BUGS again

### ISSUE THREAD

**Issue by NOMFPS** [PiMoNFeeD/csso-tracker#27]
### bugs:
-> more buy menu broken stuff
if you are spectating another team player and put "buy assaultsuit" the alive player gives helm for 
free
-> **deathmatch:**
if you type in console "buy *any" ignores spawn buy time
competitive:
you able to buy a defuser in any circumstance typing "buy defuser"

-> **Knife behavior**
remove Knifed thru smoke
the +attack2 have +attack1 sound behavior range (basically sounds knifed but don't happend)

-> **Player close to walls**
is weird to force the bug but, if you have primary weapon and you are close to a wall (front side) the other player some times don't see you
is more common see with bots, i attach some pictures
https://cdn.discordapp.com/attachments/848020561191763968/983501135178526771/player_1.rar
https://cdn.discordapp.com/attachments/848020561191763968/983501135916716032/player_2.rar

### Suggestions:

-> Remove Steam Validation System to work property with no steam clients 

-> Add cl_radar_scale

-> Performance Test on Net grapth
seeing old bug fixes like:
https://github.com/PiMoNFeeD/csso-tracker/issues/14
I compare CSS and CSSO net_grapth 3 in spectator and player movement consume a little bit more, the Usermessages have a huge weird spike
![image](https://user-images.githubusercontent.com/54552372/172260499-d7328674-29de-4a31-a296-f66dbe135a17.png)
You can take a look the bug fix to improve more with your new knowledge?

-> Reduce GPU memory usage no have way to reduce model verts like CSS? or adding LOD (i know if hard because polygons and textures but, dream is free)
![image](https://user-images.githubusercontent.com/54552372/172260547-d5e40761-749f-4a71-9de9-ba3dbbd9c059.png)

-> To reduce CSSO installation height i suggest do another CSSO installation with only current 
CSGO basic maps (without _old, operations maps, and not competitive maps) this because a lot of people play classic maps and CSS maps

**Comment by PiMoNFeeD** [comment]
> if you are spectating another team player and put "buy assaultsuit" the alive player gives helm for
free

you dont buy stuff for observed players, thats not how it works

> if you type in console "buy *any" ignores spawn buy time
> you able to buy a defuser in any circumstance typing "buy defuser"

I am pretty sure I already fixed that

> the +attack2 have +attack1 sound behavior range (basically sounds knifed but don't happend)

I am so tired of this already, I will not explain it for the 5439865934th time

> remove Knifed thru smoke

why?

> is weird to force the bug but, if you have primary weapon and you are close to a wall (front side) the other player some times don't see you

thats what it takes to not clip your weapons through walls

> Remove Steam Validation System to work property with no steam clients

no!

> Add cl_radar_scale

too much of a pain on vgui

> I compare CSS and CSSO net_grapth 3 in spectator and player movement consume a little bit more, the Usermessages have a huge weird spike

how is networking related to [maths](https://github.com/PiMoNFeeD/csso-tracker/issues/14)??? and its not even related to player movement

> Reduce GPU memory usage no have way to reduce model verts like CSS? or adding LOD (i know if hard because polygons and textures but, dream is free)

thanks I already had enough of this from you, only breaking everything with it, and either way I am here not to lower the quality of assets

> To reduce CSSO installation height i suggest do another CSSO installation with only current
CSGO basic maps (without _old, operations maps, and not competitive maps) this because a lot of people play classic maps and CSS maps

so you're telling me to keep two seemingly identical installations of csso that are NOT going to be compatible with each other due to sv_pure (because each would have their own set of VPK files) and somehow support both of them at once??
